asm("l.rfe"); // [],
asm("l.j"); // ["N"],
asm("l.bf"); // ["N"],
asm("l.bnf"); // ["N"],
asm("l.jal"); // ["N"],
asm("l.sys"); // ["K"],
asm("l.nop"); // ["K"],
asm("l.trap"); // ["K"],
asm("l.jr"); // ["rB"],
asm("l.jalr"); // ["rB"],
asm("l.movhi"); // ["rD", "K"],
asm("l.sfeq"); // ["rA", "rB"],
asm("l.sfne"); // ["rA", "rB"],
asm("l.sfges"); // ["rA", "rB"],
asm("l.sfgeu"); // ["rA", "rB"],
asm("l.sfgts"); // ["rA", "rB"],
asm("l.sfgtu"); // ["rA", "rB"],
asm("l.addi"); // ["rD", "rA", "I"],
asm("l.xori"); // ["rD", "rA", "I"],
asm("l.ori"); // ["rD", "rA", "K"],
asm("l.andi"); // ["rD", "rA", "K"],
asm("l.mfspr"); // ["rD", "rA", "K"],
asm("l.mtspr"); // ["rA", "rB", "K"],
asm("l.rori"); // ["rD", "rA", "L"],
asm("l.slli"); // ["rD", "rA", "L"],
asm("l.srai"); // ["rD", "rA", "L"],
asm("l.srli"); // ["rD", "rA", "L"],
asm("l.or"); // ["rD", "rA", "rB"],
asm("l.add"); // ["rD", "rA", "rB"],
asm("l.and"); // ["rD", "rA", "rB"],
asm("l.sll"); // ["rD", "rA", "rB"],
asm("l.sra"); // ["rD", "rA", "rB"],
asm("l.srl"); // ["rD", "rA", "rB"],
asm("l.xor"); // ["rD", "rA", "rB"],
asm("l.sb"); // ["I", "(", "rA", ")", "rB"],
asm("l.sh"); // ["I", "(", "rA", ")", "rB"],
asm("l.sw"); // ["I", "(", "rA", ")", "rB"],
asm("l.lbs"); // ["rD", "I", "(", "rA", ")"],
asm("l.lbz"); // ["rD", "I", "(", "rA", ")"],
asm("l.lhs"); // ["rD", "I", "(", "rA", ")"],
asm("l.lhz"); // ["rD", "I", "(", "rA", ")"],
asm("l.lws"); // ["rD", "I", "(", "rA", ")"],
asm("l.lwz"); // ["rD", "I", "(", "rA", ")"],